default:
    dockerfile: .jakhu/default/Dockerfile
    build: .
    ports:
        - '3000:8080'
    container_name: sample-tub-default
def:
    dockerfile: .jakhu/def/Dockerfile
    build: .
    ports:
        - '3000:8080'
    container_name: sample-tub-def
mongo:
    image: mongo
    container_name: sample-service-mongo
