# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
  - "routes/oobe.js"
  - "routes/index.js"
  - "routes/dashboard.js"
  - "routes/signup.js"
  - "routes/users.js"
  - "views/js/*.js"
  - "app.js"
