---
engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.py"
exclude_paths:
- routes/oobe.js
- routes/index.js
- routes/dashboard.js
- routes/signup.js
- routes/users.js
- views/js/*.js
- app.js
