language: node_js
node_js:
  - '4.2.3'
  - '5.1.1'
  - '0.12.9'
  - '0.10.41'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.9
os:
  - linux
services:
  - mongodb
env:
  - CXX=g++-4.8
install:
  - npm install -g bower mocha nyc codeclimate-test-reporter coffee-script
  - npm install
  - bundle install
script: make ci
