language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable" 
  - "iojs"

addons:
  apt:
    packages:
    - xbuild

os:
  - linux
  - osx

env:
  - NODE_ENV=development

script: "make tests"
  
  
