language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable"
  - "iojs"

os:
  - linux

env:
  - NODE_ENV=development

install:
  - npm install
  - bundle install
  - npm install -g bower mocha

script: "make tests"
