language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable" 
  - "iojs"

addons:
  apt:
    packages:
    - mono-xsp2-base
    - mono-xsp2

env:
  - NODE_ENV=development

script: "make tests && cd app && xbuild /p:Configuration=Release *.sln"
  
  
