language: node_js
node_js:
  - 'stable'
  - '5.4.1'
  - '5.4.0'
  - '5.3.0'
  - '4.2.6'
group: edge
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.9
os:
  - linux
services:
  - mongodb
env:
  global:
    - CXX=g++-4.8
    - JAKHU_RUN_TYPE=local
    - JAKHU_TEST=true
install:
  - npm install -g bower mocha nyc codeclimate-test-reporter coffee-script
  - npm install
  - bundle install
script: make ci
