language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - stable
  - iojs
os:
  - linux
services:
  - mongodb
env:
  - NODE_ENV=development
install:
  - npm install -g bower mocha nyc codeclimate-test-reporter coffee-script
  - npm install
  - bundle install
script: make ci
