language: node_js
node_js:
- '4.2.2'
- '4.2.1'
- '4.2.0'
- '4.1.2'
- '4.1.1'
- '4.0.0'
group: edge
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.9
os:
  - linux
services:
  - mongodb
env:
  - CXX=g++-4.8
install:
  - npm install -g bower mocha nyc codeclimate-test-reporter coffee-script
  - npm install
  - bundle install
script: make ci
